/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicArtikelBildFileIdRouteImport } from './routes/api/public/artikel-bild.$fileId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicArtikelBildFileIdRoute =
  ApiPublicArtikelBildFileIdRouteImport.update({
    id: '/api/public/artikel-bild/$fileId',
    path: '/api/public/artikel-bild/$fileId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/artikel-bild/$fileId': typeof ApiPublicArtikelBildFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/artikel-bild/$fileId': typeof ApiPublicArtikelBildFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/artikel-bild/$fileId': typeof ApiPublicArtikelBildFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/artikel-bild/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/artikel-bild/$fileId'
  id: '__root__' | '/' | '/api/public/artikel-bild/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicArtikelBildFileIdRoute: typeof ApiPublicArtikelBildFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/artikel-bild/$fileId': {
      id: '/api/public/artikel-bild/$fileId'
      path: '/api/public/artikel-bild/$fileId'
      fullPath: '/api/public/artikel-bild/$fileId'
      preLoaderRoute: typeof ApiPublicArtikelBildFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicArtikelBildFileIdRoute: ApiPublicArtikelBildFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
