/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnmeldenRouteImport } from './routes/anmelden'
import { Route as BilderRouteImport } from './routes/bilder'
import { Route as KontoRouteImport } from './routes/konto'
import { Route as ApiPublicArtikelBildFileIdRouteImport } from './routes/api/public/artikel-bild.$fileId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnmeldenRoute = AnmeldenRouteImport.update({
  id: '/anmelden',
  path: '/anmelden',
  getParentRoute: () => rootRouteImport,
} as any)
const BilderRoute = BilderRouteImport.update({
  id: '/bilder',
  path: '/bilder',
  getParentRoute: () => rootRouteImport,
} as any)
const KontoRoute = KontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicArtikelBildFileIdRoute =
  ApiPublicArtikelBildFileIdRouteImport.update({
    id: '/api/public/artikel-bild/$fileId',
    path: '/api/public/artikel-bild/$fileId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/bilder': typeof BilderRoute
  '/konto': typeof KontoRoute
  '/api/public/artikel-bild/$fileId': typeof ApiPublicArtikelBildFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/bilder': typeof BilderRoute
  '/konto': typeof KontoRoute
  '/api/public/artikel-bild/$fileId': typeof ApiPublicArtikelBildFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/bilder': typeof BilderRoute
  '/konto': typeof KontoRoute
  '/api/public/artikel-bild/$fileId': typeof ApiPublicArtikelBildFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anmelden'
    | '/bilder'
    | '/konto'
    | '/api/public/artikel-bild/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anmelden'
    | '/bilder'
    | '/konto'
    | '/api/public/artikel-bild/$fileId'
  id:
    | '__root__'
    | '/'
    | '/anmelden'
    | '/bilder'
    | '/konto'
    | '/api/public/artikel-bild/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnmeldenRoute: typeof AnmeldenRoute
  BilderRoute: typeof BilderRoute
  KontoRoute: typeof KontoRoute
  ApiPublicArtikelBildFileIdRoute: typeof ApiPublicArtikelBildFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anmelden': {
      id: '/anmelden'
      path: '/anmelden'
      fullPath: '/anmelden'
      preLoaderRoute: typeof AnmeldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilder': {
      id: '/bilder'
      path: '/bilder'
      fullPath: '/bilder'
      preLoaderRoute: typeof BilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konto': {
      id: '/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof KontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/artikel-bild/$fileId': {
      id: '/api/public/artikel-bild/$fileId'
      path: '/api/public/artikel-bild/$fileId'
      fullPath: '/api/public/artikel-bild/$fileId'
      preLoaderRoute: typeof ApiPublicArtikelBildFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnmeldenRoute: AnmeldenRoute,
  BilderRoute: BilderRoute,
  KontoRoute: KontoRoute,
  ApiPublicArtikelBildFileIdRoute: ApiPublicArtikelBildFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
