/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnmeldenRouteImport } from './routes/anmelden'
import { Route as BestellungenRouteImport } from './routes/bestellungen'
import { Route as KontoRouteImport } from './routes/konto'
import { Route as KundenanfrageRouteImport } from './routes/kundenanfrage'
import { Route as PasswortSetzenRouteImport } from './routes/passwort-setzen'
import { Route as ApiPublicArtikelBildFileIdRouteImport } from './routes/api/public/artikel-bild.$fileId'
import { Route as ApiBelegOrderIdKindIdRouteImport } from './routes/api/beleg.$orderId.$kind.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnmeldenRoute = AnmeldenRouteImport.update({
  id: '/anmelden',
  path: '/anmelden',
  getParentRoute: () => rootRouteImport,
} as any)
const BestellungenRoute = BestellungenRouteImport.update({
  id: '/bestellungen',
  path: '/bestellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const KontoRoute = KontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => rootRouteImport,
} as any)
const KundenanfrageRoute = KundenanfrageRouteImport.update({
  id: '/kundenanfrage',
  path: '/kundenanfrage',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswortSetzenRoute = PasswortSetzenRouteImport.update({
  id: '/passwort-setzen',
  path: '/passwort-setzen',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicArtikelBildFileIdRoute =
  ApiPublicArtikelBildFileIdRouteImport.update({
    id: '/api/public/artikel-bild/$fileId',
    path: '/api/public/artikel-bild/$fileId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBelegOrderIdKindIdRoute = ApiBelegOrderIdKindIdRouteImport.update({
  id: '/api/beleg/$orderId/$kind/$id',
  path: '/api/beleg/$orderId/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/bestellungen': typeof BestellungenRoute
  '/konto': typeof KontoRoute
  '/kundenanfrage': typeof KundenanfrageRoute
  '/passwort-setzen': typeof PasswortSetzenRoute
  '/api/public/artikel-bild/$fileId': typeof ApiPublicArtikelBildFileIdRoute
  '/api/beleg/$orderId/$kind/$id': typeof ApiBelegOrderIdKindIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/bestellungen': typeof BestellungenRoute
  '/konto': typeof KontoRoute
  '/kundenanfrage': typeof KundenanfrageRoute
  '/passwort-setzen': typeof PasswortSetzenRoute
  '/api/public/artikel-bild/$fileId': typeof ApiPublicArtikelBildFileIdRoute
  '/api/beleg/$orderId/$kind/$id': typeof ApiBelegOrderIdKindIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/bestellungen': typeof BestellungenRoute
  '/konto': typeof KontoRoute
  '/kundenanfrage': typeof KundenanfrageRoute
  '/passwort-setzen': typeof PasswortSetzenRoute
  '/api/public/artikel-bild/$fileId': typeof ApiPublicArtikelBildFileIdRoute
  '/api/beleg/$orderId/$kind/$id': typeof ApiBelegOrderIdKindIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anmelden'
    | '/bestellungen'
    | '/konto'
    | '/kundenanfrage'
    | '/passwort-setzen'
    | '/api/public/artikel-bild/$fileId'
    | '/api/beleg/$orderId/$kind/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anmelden'
    | '/bestellungen'
    | '/konto'
    | '/kundenanfrage'
    | '/passwort-setzen'
    | '/api/public/artikel-bild/$fileId'
    | '/api/beleg/$orderId/$kind/$id'
  id:
    | '__root__'
    | '/'
    | '/anmelden'
    | '/bestellungen'
    | '/konto'
    | '/kundenanfrage'
    | '/passwort-setzen'
    | '/api/public/artikel-bild/$fileId'
    | '/api/beleg/$orderId/$kind/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnmeldenRoute: typeof AnmeldenRoute
  BestellungenRoute: typeof BestellungenRoute
  KontoRoute: typeof KontoRoute
  KundenanfrageRoute: typeof KundenanfrageRoute
  PasswortSetzenRoute: typeof PasswortSetzenRoute
  ApiPublicArtikelBildFileIdRoute: typeof ApiPublicArtikelBildFileIdRoute
  ApiBelegOrderIdKindIdRoute: typeof ApiBelegOrderIdKindIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anmelden': {
      id: '/anmelden'
      path: '/anmelden'
      fullPath: '/anmelden'
      preLoaderRoute: typeof AnmeldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestellungen': {
      id: '/bestellungen'
      path: '/bestellungen'
      fullPath: '/bestellungen'
      preLoaderRoute: typeof BestellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konto': {
      id: '/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof KontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kundenanfrage': {
      id: '/kundenanfrage'
      path: '/kundenanfrage'
      fullPath: '/kundenanfrage'
      preLoaderRoute: typeof KundenanfrageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passwort-setzen': {
      id: '/passwort-setzen'
      path: '/passwort-setzen'
      fullPath: '/passwort-setzen'
      preLoaderRoute: typeof PasswortSetzenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/artikel-bild/$fileId': {
      id: '/api/public/artikel-bild/$fileId'
      path: '/api/public/artikel-bild/$fileId'
      fullPath: '/api/public/artikel-bild/$fileId'
      preLoaderRoute: typeof ApiPublicArtikelBildFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/beleg/$orderId/$kind/$id': {
      id: '/api/beleg/$orderId/$kind/$id'
      path: '/api/beleg/$orderId/$kind/$id'
      fullPath: '/api/beleg/$orderId/$kind/$id'
      preLoaderRoute: typeof ApiBelegOrderIdKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnmeldenRoute: AnmeldenRoute,
  BestellungenRoute: BestellungenRoute,
  KontoRoute: KontoRoute,
  KundenanfrageRoute: KundenanfrageRoute,
  PasswortSetzenRoute: PasswortSetzenRoute,
  ApiPublicArtikelBildFileIdRoute: ApiPublicArtikelBildFileIdRoute,
  ApiBelegOrderIdKindIdRoute: ApiBelegOrderIdKindIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
